---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  namespace: demo-trino
data:
  authz.rego: |
    package trino.authz

    default allow = false

    allow {
        input.context.identity.user != ""
    }

  rowfilter.rego: |
    package trino.rowfilter

    default expression = ""

    expression = sprintf("sales_rep = '%s'", [input.context.identity.user]) {
        input.action.resource.table.tableName == "orders"
        valid_user
    }

    expression = "" {
        input.action.resource.table.tableName == "orders"
        input.context.identity.user == "admin"
    }

    valid_user {
        input.context.identity.user == "alice"
    }

    valid_user {
        input.context.identity.user == "bob"
    }

    valid_user {
        input.context.identity.user == "charlie"
    }

    valid_user {
        input.context.identity.user == "diana"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: demo-trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:0.58.0
        args:
        - "run"
        - "--server"
        - "--log-level=debug"
        - "--log-format=json-pretty"
        - "/policies"
        ports:
        - containerPort: 8181
        volumeMounts:
        - name: opa-policies
          mountPath: /policies
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: opa-policies
        configMap:
          name: opa-policies

---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: demo-trino
spec:
  selector:
    app: opa
  ports:
  - name: http
    port: 8181
    targetPort: 8181
  type: ClusterIP