---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-runtime-config
  namespace: demo-trino
data:
  config.yaml: |
    services:
      authz:
        url: http://localhost:8181

    bundles:
      authz:
        persist: true
        polling:
          min_delay_seconds: 10
          max_delay_seconds: 20

    decision_logs:
      console: true

    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        enable_reflection: true