---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: demo-trino
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://localhost:8080

  jvm.config: |
    -server
    -Xmx2G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true

  node.properties: |
    node.environment=production
    node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
    node.data-dir=/data/trino

  log.properties: |
    io.trino=INFO
    io.trino.plugin.postgresql=DEBUG
    io.trino.plugin.opa=DEBUG

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
  namespace: demo-trino
data:
  postgresql.properties: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgres:5432/demo
    connection-user=trino
    connection-password=trinopass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: demo-trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - name: trino
        image: trinodb/trino:461
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Dfile.encoding=UTF-8"
        volumeMounts:
        - name: trino-config
          mountPath: /etc/trino
        - name: trino-catalog
          mountPath: /etc/trino/catalog
        - name: trino-data
          mountPath: /data/trino
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /v1/info
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/info
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: trino-config
        configMap:
          name: trino-config
      - name: trino-catalog
        configMap:
          name: trino-catalog
      - name: trino-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: demo-trino
spec:
  selector:
    app: trino
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP