---
apiVersion: v1
kind: Secret
metadata:
  name: opa-api-credentials
  namespace: demo-trino
type: Opaque
data:
  # Basic auth for u1:p1 (base64 encoded)
  # echo -n "u1:p1" | base64
  basic_auth_token: dTE6cDE=
stringData:
  username: "u1"
  password: "p1"